/* eslint-disable @next/next/no-html-link-for-pages */
import Image from"next/image";import{brands}from"@/data/brands";import{locations}from"@/data/locations";import{company}from"@/data/company";
const promises=[["◇","Fresh Ingredients","Quality ingredients selected carefully."],["♨","Expertly Prepared","Food made by trained kitchen teams."],["→","Reliable Delivery","Built from the ground up for delivery."],["♡","Made With Care","Consistency in every order."]];
export default function Home(){return <><section className="hero"><Image src="/images/hero/hero-food.png" alt="Salmon sushi and creamy pasta" fill priority sizes="100vw"/><div className="hero-shade"/><div className="hero-copy"><p className="eyebrow">Good food. Made right. Delivered.</p><h1>Food experiences<br/>people <em>love.</em></h1><p>Wedeliver Inc. brings together food brands built around one simple idea: great food, made with care and delivered reliably.</p><a className="button" href="#brands">Explore our brands →</a></div></section>
<section id="brands" className="section"><div className="section-head"><p className="eyebrow">Our brands</p><h2>Two brands. One promise.</h2><p>Quality ingredients. Expertly made. Delivered to you.</p></div><div className="brand-grid">{brands.map((b,i)=><article className={`brand-card ${b.theme}`} key={b.name}><Image className="brand-bg" src={b.image} alt="" fill sizes="(max-width: 900px) 100vw, 50vw"/><div className="brand-overlay"/><div className="brand-content"><Image src={b.logo} alt={`${b.name} official logo`} width={190} height={120}/><p>{b.description}</p><a href={b.url} target="_blank" rel="noreferrer" className="outline-button">Order from {i?"pasta.ph":"mysushi.ph"} →</a><a href={`/brands#${b.slug}`} className="brand-more-link">More info about {b.name} →</a></div></article>)}</div><div className="promise-grid">{promises.map(([i,t,d])=><div key={t}><span>{i}</span><h3>{t}</h3><p>{d}</p></div>)}</div></section>
<section className="about-split"><div className="about-copy"><p className="eyebrow">Who we are</p><h2>Driven by passion.<br/>Committed to quality.</h2><p>Wedeliver Inc. is a Philippine food company created to build and operate exceptional food brands designed for today’s delivery-driven market.</p><p>From our kitchens to our customers’ tables, we focus on quality ingredients, disciplined preparation, consistency and reliable service.</p><a className="text-link" href="/about">More about us →</a></div><div className="kitchen-photo"><Image src="/images/kitchens/kitchen-team.png" alt="Kitchen team preparing sushi and pasta" fill/><div className="values-card"><p className="eyebrow">Our values</p>{["Quality First","Consistency","Teamwork","Customer Satisfaction"].map(x=><div key={x}>◇ <span>{x}</span></div>)}</div></div></section>
<section className="section kitchens"><div className="section-head left"><p className="eyebrow">Our kitchens</p><h2>Strategically located.<br/>Always cooking for you.</h2><p>Our multi-brand kitchens serve customers efficiently across key areas of Metro Manila.</p></div><div className="location-grid">{locations.map(l=><article key={l.name}><h3>{l.name}</h3>{l.lines.map(x=><p key={x}>{x}</p>)}<p className="served">MySushi · Pasta Bella</p></article>)}<article className="soon"><span>⌖</span><p className="eyebrow">Expanding soon</p><h3>More kitchens.<br/>More locations.<br/>More good food.</h3></article></div></section>
<section className="stats">{company.stats.map(s=><div key={s.label}><strong>{s.value}</strong><span>{s.label}</span></div>)}</section>
<section className="section partnership"><div><p className="eyebrow">Work with us</p><h2>More than food delivery.</h2><p>Wedeliver works with companies, condominiums, offices, bars, hotels and event organizers throughout Metro Manila.</p><a className="button" href="/contact?subject=partnership">Become a partner →</a></div><div className="partner-grid">{[["Corporate Orders","Meal solutions for meetings, celebrations and company events."],["Condominium Partnerships","Exclusive offers and food programs for condominium communities."],["Hotels & Hospitality","Reliable food solutions and partnership opportunities."],["Bars & Venues","Food partnerships designed to complement your beverage offering."]].map(([t,d])=><article key={t}><span>◇</span><h3>{t}</h3><p>{d}</p></article>)}</div></section><section className="contact-cta"><p className="eyebrow">Start a conversation</p><h2>Let’s work together.</h2><p>Corporate orders, partnerships, or questions—we’d love to hear from you.</p><a className="button" href="/contact">Contact Wedeliver →</a></section></>}
